### ISSUE TITLE
@haspermissionto directive

### ISSUE THREAD

**Issue by Cadienvan** [Laravel-Backpack/PermissionManager#69] opened 2017-03-22 15:50 UTC
Is there any kind of @haspermissionto directive?

How do I show admin sidebar items depending on user's permission to do / not to do stuff?
Right now I can only use roles, and it doesn't allow me to specify multi-purposes users..

**Comment by lloy0076** [comment] 2017-04-06 17:09
@Cadienvan  - > https://github.com/Laravel-Backpack/PermissionManager#using-blade-directives

You can use "@can" for permissions!

**Comment by AbbyJanke** [comment] 2017-04-07 18:45
I am kind of curious about this too. so @can works if the user has the direct permission but doesn't check through roles. Any thoughts on how we can work around this? :)

**Comment by OwenMelbz** [comment] 2017-04-07 18:47
Check both ☺️ I think these come from the Spatie permissions packAge, so maybe checkout the docs over there

**Comment by AbbyJanke** [comment] 2017-04-07 18:48
That is an option but the problem is that I am assigning that same role to a few different roles. I want it to be more dynamic so I can add/remove roles as I need to with specific permissions. I will check over at Spatie's section.

**Comment by lloy0076** [comment] 2017-04-08 15:07
```
@if (Auth::user()->hasPermissionTo('whatever')
<b>Wow I can!</b>
@endif
```

**Comment by lloy0076** [comment] 2017-07-05 20:26
@Cadienvan @AbbyJanke @OwenMelbz - this seems more an upstream issue than a Backpack one *although* I suspect upstream `laravel-permission` would benefit from a PR that searched all permissions, including ones added by roles...I'd be inclined to close it?

**Comment by Cadienvan** [comment] 2017-07-05 20:34
@lloy0076 Guess so, right now I'm not working with Backpack anymore (Got stuck at Client-Side stuff), so I'll not be able to PR laravel-permission, can I ask @AbbyJanke or @OwenMelbz to help with that?

**Comment by lloy0076** [comment] 2017-08-13 12:19
@AbbyJanke - IIRC there might have been a suggested PR from you or at least we were discussing this in gitter?

In the absence of a PR (at least one I can find) I'm closing this for now.

**Closed by lloy0076** 2017-08-13 12:19 UTC
