### ISSUE TITLE
Cant see or add users, roles, permissions - Laravel 5.4

### ISSUE THREAD

**Issue by Hadza** [Laravel-Backpack/PermissionManager#71] opened 2017-03-25 16:15 UTC
When i get into the Users view i get:
DataTables warning: table id=crudTable - Ajax error. For more information about this error, please see http://datatables.net/tn/

And when i try to add roles/permissions i get:
ErrorException in Builder.php line 2445: Call to undefined method Illuminate\Database\Query\Builder::translationEnabled() (View: C:\xampp\htdocs\adminlc\vendor\backpack\crud\src\resources\views\form_content.blade.php) (View: C:\xampp\htdocs\adminlc\vendor\backpack\crud\src\resources\views\form_content.blade.php)

**Comment by jhivan** [comment] 2017-03-26 13:39
Have you changed the default users database that ships with laravel? (for example have you changed the `name` field to `username`?)

**Comment by Hadza** [comment] 2017-03-26 15:24
No, i havent changed anything, just went from fresh project and install everything

**Comment by hotsaucejake** [comment] 2017-04-20 02:38
@jhivan I changed the the default users database from ````name```` to ````username````

Is there a fix for this?

**Comment by abolinhas** [comment] 2017-04-25 17:50
+1

**Comment by valeryan** [comment] 2017-05-25 22:01
I have a similar error with permissions. I can add users but I can't add roles or permissions without getting this error. 

This is clean install of Laravel 5.4 following the installation guide. I have to two traits in my user model.

**The Error:**
```
Call to undefined method Illuminate\Database\Query\Builder::translationEnabled() 
(View:.../Projects/backpack/resources/views/vendor/backpack/crud/form_content.blade.php) 
(View:..../Projects/backpack/resources/views/vendor/backpack/crud/form_content.blade.php)
```

**My User Model**
```php
<?php

namespace App;

use Backpack\Base\app\Notifications\ResetPasswordNotification as ResetPasswordNotification;
use Backpack\CRUD\CrudTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use CrudTrait;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
     /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }
}
```

**Comment by jesusvpct** [comment] 2017-06-13 17:33
The same problem here. I'm using a clean Laravel 5.4 installation and I can't add roles/permissions. It seems that there is something wrong related to language.

**Comment by lloy0076** [comment] 2017-06-13 20:00
This occurs when the CrudTrait cannot be found on the relevant models.

All the following models will need that trait:

* The **User** model, *usually* `app/User.php` but some people shift this about
* The **Permission** model, *usually* the one from https://github.com/Laravel-Backpack/PermissionManager/blob/master/src/app/Models/Permission.php
* The **Role** model, *usually* the one from https://github.com/Laravel-Backpack/PermissionManager/blob/master/src/app/Models/Permission.php

If you've followed the instructions then these should all "just work"; if you've changed **any** authentication guards, anything to do with `laravel-permission`'s configuration then this may happen.

You'll find relevant logs in `storage/logs/laravel.log` and it would be interesting to see precisely which model doesn't have the `translatable` trait.

TBH, this is probably a small but important misconfiguration as I set these up a few times a week for testing and haven't noticed a break - this doesn't mean there isn't something odd but I haven't, yet, noticed this behaviour - at least as of around this date (give or take 1-2 weeks).

**Comment by jesusvpct** [comment] 2017-06-14 15:53
The errors are the same that posted valeryan, and I've installed step by step with the instructions from backpack page, and this github repository. Adding a User works fine, but Role/Permissions not. When clicking on Add Role button, I get the error (the same on laravel.log):

> (3/3) ErrorException
> 
> Call to undefined method Illuminate\Database\Query\Builder::translationEnabled() (View: /media/jesus/HP Desktop Drive/Proyectos/test1/vendor/backpack/crud/src/resources/views/form_content.blade.php) (View: /media/jesus/HP Desktop Drive/Proyectos/test1/vendor/backpack/crud/src/resources/views/form_content.blade.php)
> in Builder.php (line 2450)
> at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php (line 44)
> at PhpEngine->evaluatePath('/media/jesus/HP Desktop Drive/Proyectos/test1/storage/framework/views/1cc15fb8b6d4977571eed32be7f867249a9ea27d.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'crud' => object(CrudPanel), 'saveAction' => array('active' => array('value' => 'save_and_back', 'label' => 'Save and back'), 'options' => array('save_and_edit' => 'Save and edit this item', 'save_and_new' => 'Save and new item')), 'fields' => array('name' => array('name' => 'name', 'label' => 'Name', 'type' => 'text'), 'permissions' => array('label' => 'Permissions', 'type' => 'checklist', 'name' => 'permissions', 'entity' => 'permissions', 'attribute' => 'name', 'model' => 'Backpack\\PermissionManager\\app\\Models\\Permission', 'pivot' => true)), 'title' => 'Add Role'))in CompilerEngine.php (line 59)
> at CompilerEngine->get('/media/jesus/HP Desktop Drive/Proyectos/test1/vendor/backpack/crud/src/resources/views/create.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'crud' => object(CrudPanel), 'saveAction' => array('active' => array('value' => 'save_and_back', 'label' => 'Save and back'), 'options' => array('save_and_edit' => 'Save and edit this item', 'save_and_new' => 'Save and new item')), 'fields' => array('name' => array('name' => 'name', 'label' => 'Name', 'type' => 'text'), 'permissions' => array('label' => 'Permissions', 'type' => 'checklist', 'name' => 'permissions', 'entity' => 'permissions', 'attribute' => 'name', 'model' => 'Backpack\\PermissionManager\\app\\Models\\Permission', 'pivot' => true)), 'title' => 'Add Role'))in View.php (line 137)

There are more errors lines, but I think that these ones are enough.

And when clicking on Add Permission button:

> (3/3) ErrorException
> 
> Call to undefined method Illuminate\Database\Query\Builder::translationEnabled() (View: /media/jesus/HP Desktop Drive/Proyectos/test1/vendor/backpack/crud/src/resources/views/form_content.blade.php) (View: /media/jesus/HP Desktop Drive/Proyectos/test1/vendor/backpack/crud/src/resources/views/form_content.blade.php)
> in Builder.php (line 2450)
> at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php (line 44)
> at PhpEngine->evaluatePath('/media/jesus/HP Desktop Drive/Proyectos/test1/storage/framework/views/1cc15fb8b6d4977571eed32be7f867249a9ea27d.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'crud' => object(CrudPanel), 'saveAction' => array('active' => array('value' => 'save_and_back', 'label' => 'Save and back'), 'options' => array('save_and_edit' => 'Save and edit this item', 'save_and_new' => 'Save and new item')), 'fields' => array('name' => array('name' => 'name', 'label' => 'Name', 'type' => 'text'), 'roles' => array('label' => 'Roles', 'type' => 'checklist', 'name' => 'roles', 'entity' => 'roles', 'attribute' => 'name', 'model' => 'Backpack\\PermissionManager\\app\\Models\\Role', 'pivot' => true)), 'title' => 'Add permission'))in CompilerEngine.php (line 59)
> at CompilerEngine->get('/media/jesus/HP Desktop Drive/Proyectos/test1/vendor/backpack/crud/src/resources/views/create.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'crud' => object(CrudPanel), 'saveAction' => array('active' => array('value' => 'save_and_back', 'label' => 'Save and back'), 'options' => array('save_and_edit' => 'Save and edit this item', 'save_and_new' => 'Save and new item')), 'fields' => array('name' => array('name' => 'name', 'label' => 'Name', 'type' => 'text'), 'roles' => array('label' => 'Roles', 'type' => 'checklist', 'name' => 'roles', 'entity' => 'roles', 'attribute' => 'name', 'model' => 'Backpack\\PermissionManager\\app\\Models\\Role', 'pivot' => true)), 'title' => 'Add permission'))in View.php (line 137)

**Comment by zulfajuniadi** [comment] 2017-06-15 15:21
I've also ran into this problem and fixed it by doing the following:

File: `config/laravel-permission.php` 

line 16:

Change:

```php
        'permission' => Spatie\Permission\Models\Permission::class,
```

To:

```php
        'permission' => Backpack\PermissionManager\app\Models\Permission::class,
```

line 27:

Change:

```php
        'permission' => Spatie\Permission\Models\Permission::class,
```

To:

```php
        'role' => Backpack\PermissionManager\app\Models\Role::class,
```

**Comment by jesusvpct** [comment] 2017-06-15 16:39
@zulfajuniadi Thanks, this works for Permissions/Roles, but now Users is not working. So, without that configuration, Users works, and with that configuration, Users not work. Very strange...

**Comment by lloy0076** [comment] 2017-06-16 02:34
Hmmm, the default configuration _if_ installed precisely as in the backpack docs (*not* the spatie/laravel-permission upstream docs) should have this correct already.

My main glitch is I can't make this misconfiguration occur on Laravel 5.4 and the latest backpack release.

I'm tempted to close this as fixed but I'm not convinced there isn't something obscure that trips people up even though they've followed the backpack install instructions precisely.

**Comment by valeryan** [comment] 2017-07-02 02:38
I did a fresh install of laravel and added only the base, crud, and roles and it all works. I think the glitch happens when one of the other backpack packages is installed. In my other install that has this error. I have the lang and page package installed as well. I would bet that the problem is with one of the other packages  in some way. I have not been able to spend time working on the project I am using backpack with at the moment or I would try to provide more insight.

**Comment by AbbyJanke** [comment] 2017-07-02 03:57
The page package does not cause any issues with permission manager. It is likely due to translation if it is related.

**Comment by Hadza** [comment] 2017-07-03 20:04
I made another clean install, Laravel->Base->CRUD->Permission Manager, and still get the same results, i didnt change anything, just installed those three.

**Comment by gluxon** [comment] 2017-07-03 20:30
When this issue happened for me, I think I caused it by running `php artisan vendor:publish` instead of following the instructions and running `php artisan vendor:publish --provider="Backpack\PermissionManager\PermissionManagerServiceProvider"` first.

My `config/laravel-permission.php` file didn't just have the permission and user models incorrect, but the entire file was spatie's version instead of Laravel Backpack's version. My guess is that spatie's `vendor:publish` register typically runs before Laravel Backpack.

**Comment by valeryan** [comment] 2017-07-03 20:49
@gluxon I think you are right. I often run `vendor:publish` after adding lots of packages in laravel projects and this package does not seem to work well with just running `vendor publish`.  It also creates a new migration every time you run `vendor publish` which can cause some issues. But if you run `vendor:publish` instead of specifically running `php artisan vendor:publish --provider="Backpack\PermissionManager\PermissionManagerServiceProvider"` you get the wrong config file for permissions.

**Comment by lloy0076** [comment] 2017-07-03 20:49
@gluxon - you're right; in which case this isn't really a bug...

**Closed** 2017-07-06 07:54 UTC

**Comment by CHOMNANP** [comment] 2017-10-02 17:10
How does the issue got fixed?

**Comment by valeryan** [comment] 2017-10-02 18:05
@CHOMNANP I have not looked at this issue in some time. However, If I remember correctly the problem is that the wrong configuration file is pushed if you simply do `vendor:publish`. To fix the issue you just have to get a copy of the correct config from your vendor folder and copy it to the app config folder. You will want to get `laravel-permission.php` from `Backpack\PermissionManager`.

**Comment by CHOMNANP** [comment] 2017-10-03 03:41
I got it fixed by following @zulfajuniadi on replacing "Spatie" with "Backpack\PermissionManager" class. Thanks.

**Comment by SilenceM59** [comment] 2018-05-24 01:50
Yep, replacing the two lines fixed it for me as well.

**Comment by tabacitu** [comment] 2018-06-04 07:29
@NHuebner1983 we're on it :-) Pretty soon all packages will have a one-line install and setup. So you'll be able to copy-paste 6 lines of code in your terminal and it'll install and setup all 6 packages.
