### ISSUE TITLE
App\User::isTranslatableAttribute() must be of the type string, array given

### ISSUE THREAD

**Issue by defmost** [Laravel-Backpack/PermissionManager#257] opened 2020-11-13 00:45 UTC
I have an error when HasTranslations trait is on the User Model

I realise that the field checklist_dependency has on the name an array and the Spatie Translation expect a string.

Is there any quick fix to make it work?

Please see the screenshot attached
![Screen Shot 2020-11-13 at 11 41 49 am](https://user-images.githubusercontent.com/9258607/99013723-4a38cc80-25a5-11eb-855e-9a8231b2def0.png)
![Screen Shot 2020-11-13 at 11 41 33 am](https://user-images.githubusercontent.com/9258607/99013730-4d33bd00-25a5-11eb-8c32-d94034070cec.png)

Thanks

**Comment by promatik** [comment] 2020-11-13 11:45
@defmost I was able to reproduce the problem, in fact it happens because there are multiple fields inside a single field instance.
But it doesn't make too much sense, because you can't translate roles or permissions, an User can't have different roles or different permissions when he changes the page language, does he?

**Comment by promatik** [comment] 2020-11-14 10:40
@defmost I just open a PR with the fix.
Let's move the conversation to there: https://github.com/Laravel-Backpack/CRUD/pull/3327, let's hope it's merged as soon as possible ✌

**Closed by promatik** 2020-11-14 10:40 UTC
Labels: bug
