### ISSUE TITLE
Create button still exists if the allow_permission_create and allow_role_create options are false

### ISSUE THREAD

**Issue by mialex** [Laravel-Backpack/PermissionManager#221] opened 2020-03-01 06:11 UTC
# Bug report
When **allow_permission_create** and **allow_role_create** options are turned off (marked as **false**), the Create button int the top of the list of roles and permissions still exists.

### What I did:

Under the **config/backpack/permissionmanager.php** I've turned off create permissions (actually I disabled all of them) and I can see that these Actions are not Allowed anymore

### What I expected to happen:

When those options are turned off, I would expect that on the list page there won't be the **Create Role** or **Create Permission** button

### What happened:

Actually, the **Create Role** or **Create Permission** buttons exist in the top of roles and permissions pages and when you click them, you get 403 error, as this actin is restricted

### What I've already tried to fix it:

I haven't tried to fix as this is an external library

### Backpack, Laravel, PHP, DB version:
"backpack/crud" : "4.0.40"
"laravel/framework" : "v6.15.1"

**Comment by tabacitu** [comment] 2020-03-01 11:40
Hmm... I don't know what to advise @mialex , I just tested it and it worked fine for me:
![2020-03-01 13 38 22](https://user-images.githubusercontent.com/1032474/75624953-15751880-5bc2-11ea-917c-7f6eddb3bcbb.gif)

Are you sure it's not something you've done? Maybe you've overwritten the ```create``` button and it no longer has ```@if ($crud->hasAccess('create'))``` inside it?

Cheers!

PS. Closing since I couldn't reproduce it. We'll reopen if more information proves it's a bug inside Backpack.

**Closed by tabacitu** 2020-03-01 11:40 UTC
Labels: triage

**Comment by pxpm** [comment] 2020-03-02 10:19
Maybe a `php artisan config:cache` would solve it.
