### ISSUE TITLE
@can('permission') directive and @if(backpack_user()->can('permission'))  is not working with multiple auth guard

### ISSUE THREAD

**Issue by drionix** [Laravel-Backpack/PermissionManager#246] opened 2020-08-11 06:05 UTC
# Bug report

### What I did:
Use `@can('permission')` or `@if(backpack_user()->can('permission'))` with `'backpack'` auth guard

### What I expected to happen:
Return the correct true/false value

### What happened:
Always return false

### What I've already tried to fix it:
Use `@if(backpack_user()->hasPermissionTo('permission', 'guard'))` instead.

The reason is because spatie/laravel-permission did not take custom guard into account when registering Gate permission. Thus, `@can('permission')` or `@if(backpack_user()->can('permission'))` always use `web` auth guard by default and always return false if the permission is saved to database using `backpack` auth.

```
public function registerPermissions(): bool
    {
        app(Gate::class)->before(function (Authorizable $user, string $ability) {
            if (method_exists($user, 'checkPermissionTo')) {
                return $user->checkPermissionTo($ability) ?: null;
            }
        });


        return true;
    }
```

https://github.com/spatie/laravel-permission/blob/bf539b1f290b097061f564f683411de6e490d9ad/src/PermissionRegistrar.php#L86-L95

I point this out hoping that the documentation of this package could be updated because it is suggesting that we can use `@can('permission')` directive or `@if(backpack_user()->can('permission'))` with multiple auth guard.

### PHP VERSION:
PHP 7.3.12
### LARAVEL VERSION:
v7.12.0
### BACKPACK VERSION:
4.1.16

**Comment by conschneider** [comment] 2020-10-16 13:06
Hi, 

I can confirm the behaviour. While I have not have time to test multiple guard / setup combos, I had the same experience. Ultimately I am currently using the `web` guard on all permissions so I can use the `@can` blade directive.

**Comment by soufiene-slimi** [comment] 2021-01-07 22:38
Hi @drionix, for a quick and permanent solution, try separating the backpack user from the user used by Laravel guard, here what you need to do:
- Create `app\Models\BackpackUser.php`
```php
<?php

namespace App\Models;

use App\User;
use Illuminate\Notifications\Notifiable;
use Backpack\CRUD\app\Notifications\ResetPasswordNotification as ResetPasswordNotification;

class BackpackUser extends User
{
    use Notifiable;

    protected $table = 'admins';

    /**
     * Send the password reset notification.
     *
     * @param string $token
     *
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }

    /**
     * Get the e-mail address where password reset links are sent.
     *
     * @return string
     */
    public function getEmailForPasswordReset()
    {
        return $this->email;
    }
}
```
- The `app\User.php` should look like this:

```php
<?php

namespace App;

use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use CrudTrait;
    use HasRoles;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}
```
- Update `config\backpack\base.php`
```php
    // Fully qualified namespace of the User model
    // 'user_model_fqn' => config('auth.providers.users.model'),
    'user_model_fqn' => App\Models\BackpackUser::class, // works on Laravel <= 7
    // 'user_model_fqn' => App\Models\User::class, // works on Laravel >= 8

    // The classes for the middleware to check if the visitor is an admin
    // Can be a single class or an array of classes
    'middleware_class' => [
        App\Http\Middleware\CheckIfAdmin::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \Backpack\CRUD\app\Http\Middleware\UseBackpackAuthGuardInsteadOfDefaultAuthGuard::class,
    ],
```

**Comment by pxpm** [comment] 2021-01-11 11:50
Hey @drionix thanks for the report.

I think the problem relies in the fact that you seeded your permissions with wrong guard ? 

https://spatie.be/docs/laravel-permission/v3/basic-usage/multiple-guards

If you didn't specify the guard manually, spatie will use the first defined in the guards array configuration. Change backpack guard to be the first in the list, or specify the guard when creating the permissions. 

Am I missing the point here or something ? 

Let me know,
Pedro

**Comment by promatik** [comment] 2021-02-14 23:57
Hi everyone!
Since this issue is in `needs-more-info` state for a long time, I'll close it for now.
@drionix if you have any more info about this, or even if this is still an issue, please re-open 🙌

**Closed by promatik** 2021-02-14 23:57 UTC
Labels: needs-more-info
