### ISSUE TITLE
How to change Roles permission to another CrudController

### ISSUE THREAD

**Issue by ainnamran20** [Laravel-Backpack/PermissionManager#309] opened 2022-08-12 01:29 UTC
![image](https://user-images.githubusercontent.com/108723258/184268431-1bac3aa5-1982-4172-bf48-65422676538e.png)

I would like to change the Roles Permission in another CrudController into which is i want to put it in the DepartmentCrudController. It is below the Kepala Department and as i highlighted in red color. Is there any possible way to do it ?

![image](https://user-images.githubusercontent.com/108723258/184268538-ecaeb5d9-2b00-4104-b837-d9b80ec2d445.png)

I really appreciate your help and thank you in advance

**Comment by tabacitu** [comment] 2022-08-12 06:03
Hi @ainnamran20 ,

This package is just an interface for [spatie/laravel-permission](https://github.com/spatie/laravel-permission) - we don't plan on adding extra features. Since we don't plan on adding Departments, and this is not a bug, I'm going to close the issue.

But I'll try to help you with direction. Sounds to me like you want to 
- create a relationship between the Department model and the Permission model (take a look at [the hasMany relationship in Laravel](https://laravel.com/docs/9.x/eloquent-relationships#one-to-many), or at how it's done in this package for the Roles);
- do the same thing in DepartmentController as we do in RolesController;
- look into the [spatie/laravel-permission](https://github.com/spatie/laravel-permission) code, do the same thing they did to Roles (access methods) to your Departments and add similar Blade helpers for departments;

I believe that's about it, but it's not exactly easy. 
Hope it helps.

Cheers!

**Closed by tabacitu** 2022-08-12 06:03 UTC
